In [6]:
x=30
y=10

In [7]:
print(x,y)

30 10


In [5]:
import numpy as np

array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1)

[[11, 12, 13, 14], [22, 23, 24, 25], [3, 34, 35, 36]]


In [2]:
print(array1)

[[11 12 13 14]
 [22 23 24 25]
 [ 3 34 35 36]]


In [3]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2)

[1 2 3 4]


In [6]:
array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1_new.ndim)

2


In [7]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2.ndim)

1


In [8]:
print(array1_new.shape)

(3, 4)


In [9]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25  3]
 [34 35 36]]


In [10]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [ 3 34]
 [35 36]]


In [11]:
array2=array1_new.reshape(12,1)
print(array2)

[[11]
 [12]
 [13]
 [14]
 [22]
 [23]
 [24]
 [25]
 [ 3]
 [34]
 [35]
 [36]]


In [12]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25  3 34 35 36]]


In [27]:
array1=np.arange(-10,10,2)
print(array1)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [29]:
array2=array1.reshape(2,5)
print(array2)

[[-10  -8  -6  -4  -2]
 [  0   2   4   6   8]]


In [33]:
import numpy as np

x = np.empty((3, 2), dtype=int) 
print(x)

[[25895968444448860 23925768161198147]
 [32370111954616435 29273891506421852]
 [18296268630392929 27303364806049904]]


In [38]:
x1=np.zeros(5)
print(x1)

[0. 0. 0. 0. 0.]


In [40]:
x = np.zeros((5,3),dtype=float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
x = np.zeros((5,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [42]:
array =np.random.randint(0,100,(10,5))
print(array)

[[44 53 86 52  3]
 [41 90 61 61 69]
 [56 61 48 52 19]
 [13 62  9 88  6]
 [65 78 77 63 99]
 [ 9  7 45 71 95]
 [80 92  0  2 13]
 [66 84 29 71 78]
 [95 81 48 63 23]
 [34 94 98 86 75]]


In [47]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1+array2
print('array1: ',array1)
print('array2: ',array2)
print('array3: ',array3)

array1:  [[19 43 80]
 [87 88 19]
 [99 83 68]
 [66 13 56]]
array2:  [[88 25  4]
 [90 64  0]
 [70 22 74]
 [ 8 42 56]]
array3:  [[107  68  84]
 [177 152  19]
 [169 105 142]
 [ 74  55 112]]
