In [6]:
x=30
y=10

In [7]:
print(x,y)

30 10


In [5]:
import numpy as np

array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1)

[[11, 12, 13, 14], [22, 23, 24, 25], [3, 34, 35, 36]]


In [2]:
print(array1)

[[11 12 13 14]
 [22 23 24 25]
 [ 3 34 35 36]]


In [3]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2)

[1 2 3 4]


In [6]:
array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1_new.ndim)

2


In [7]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2.ndim)

1


In [8]:
print(array1_new.shape)

(3, 4)


In [9]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25  3]
 [34 35 36]]


In [10]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [ 3 34]
 [35 36]]


In [ ]:
array2=array1_new.reshape(12,2)
print(array2)