In [6]:
x=30
y=10

In [7]:
print(x,y)

30 10


In [5]:
import numpy as np

array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1)

[[11, 12, 13, 14], [22, 23, 24, 25], [3, 34, 35, 36]]


In [2]:
print(array1)

[[11 12 13 14]
 [22 23 24 25]
 [ 3 34 35 36]]


In [3]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2)

[1 2 3 4]


In [6]:
array1 =[[11,12,13,14],
         [22,23,24,25],
         [3,34,35,36]]

array1_new=np.array(array1)
print(array1_new.ndim)

2


In [7]:
x=[1,2,3,4]

array2=np.array(x)
#array2=np.asarray(x)
print(array2.ndim)

1


In [8]:
print(array1_new.shape)

(3, 4)


In [9]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25  3]
 [34 35 36]]


In [10]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [ 3 34]
 [35 36]]


In [11]:
array2=array1_new.reshape(12,1)
print(array2)

[[11]
 [12]
 [13]
 [14]
 [22]
 [23]
 [24]
 [25]
 [ 3]
 [34]
 [35]
 [36]]


In [12]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25  3 34 35 36]]


In [27]:
array1=np.arange(-10,10,2)
print(array1)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [29]:
array2=array1.reshape(2,5)
print(array2)

[[-10  -8  -6  -4  -2]
 [  0   2   4   6   8]]


In [33]:
import numpy as np

x = np.empty((3, 2), dtype=int) 
print(x)

[[25895968444448860 23925768161198147]
 [32370111954616435 29273891506421852]
 [18296268630392929 27303364806049904]]


In [38]:
x1=np.zeros(5)
print(x1)

[0. 0. 0. 0. 0.]


In [40]:
x = np.zeros((5,3),dtype=float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
x = np.zeros((5,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [42]:
array =np.random.randint(0,100,(10,5))
print(array)

[[44 53 86 52  3]
 [41 90 61 61 69]
 [56 61 48 52 19]
 [13 62  9 88  6]
 [65 78 77 63 99]
 [ 9  7 45 71 95]
 [80 92  0  2 13]
 [66 84 29 71 78]
 [95 81 48 63 23]
 [34 94 98 86 75]]


In [47]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1+array2
print('array1: ',array1)
print('array2: ',array2)
print('array3: ',array3)

array1:  [[19 43 80]
 [87 88 19]
 [99 83 68]
 [66 13 56]]
array2:  [[88 25  4]
 [90 64  0]
 [70 22 74]
 [ 8 42 56]]
array3:  [[107  68  84]
 [177 152  19]
 [169 105 142]
 [ 74  55 112]]


In [2]:
import numpy as np

array1=np.random.randint(0,100,(4,3))
array2=array1/10

print('array1: ',array1)
print('array2: ',array2)

array1:  [[65 28 82]
 [64 40  2]
 [84 60 31]
 [27 86 59]]
array2:  [[6.5 2.8 8.2]
 [6.4 4.  0.2]
 [8.4 6.  3.1]
 [2.7 8.6 5.9]]


In [3]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array3=array1*array2
print('array1: ',array1)
print('array2: ',array2)
print('array3: ',array3)

array1:  [[ 3 74 69]
 [45 28 25]
 [67 56 88]
 [28 81 27]]
array2:  [[63 65 99]
 [10 12 15]
 [77 56 57]
 [86 66 71]]
array3:  [[ 189 4810 6831]
 [ 450  336  375]
 [5159 3136 5016]
 [2408 5346 1917]]


In [7]:
import numpy as np

array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))
array4=np.matmul(array1,array2.T)
print('array1: ',array1)
print('array2: ',array2)
print('array4: ',array4)

array1:  [[85 45 92]
 [83 80 32]
 [13 34 75]
 [17 88 37]]
array2:  [[80  2 62]
 [79 19 18]
 [48 67  9]
 [42 95 39]]
array4:  [[12594  9226  7923 11433]
 [ 8784  8653  9632 12334]
 [ 5758  3023  3577  6701]
 [ 3830  3681  7045 10517]]


In [11]:
array=np.random.randint(0,100,(5,7))
print(array)

[[46  7 57 69 57 77  7]
 [48 17 21 74 18 21 45]
 [ 2 49 30 86 23 22 27]
 [90 47 89 14 92 63 29]
 [95 48 21 13 19 65 77]]


In [13]:
print(np.max(array))

95


In [14]:
print(np.argmax(array))

28


In [15]:
print(np.max(array,axis=0))

[95 49 89 86 92 77 77]


In [18]:
print(np.argmax(array,axis=0))

[4 2 3 2 3 0 4]


In [16]:
print(np.max(array,axis=1))

[77 74 86 92 95]


In [19]:
print(np.argmax(array,axis=1))

[5 3 3 4 0]


In [20]:
print(array[0][2])

57


In [22]:
print(array[0:3,2:4])

[[57 69]
 [21 74]
 [30 86]]


In [23]:
print(np.mean(array))

44.714285714285715


In [24]:
print(np.sum(array))

1565


In [25]:
print(np.min(array))

2


In [26]:
print(np.mean(array,axis=0))

[56.2 33.6 43.6 51.2 41.8 49.6 37. ]


In [27]:
array5=np.random.randint(0,100,(5,10))
print(array5)

[[ 3 43 82  4 26 28 33  9  7  7]
 [ 7 15 89 68  1 64 58 13 49 47]
 [43 15 62 92 30 94 10 11 79 31]
 [86  9 21 25 39 56 67  4 89 10]
 [15 57 89 90 30 34 66 90 61 97]]


In [28]:
print(array5[2,3])

92


In [29]:
print(array5[0:2,0:4])

[[ 3 43 82  4]
 [ 7 15 89 68]]


In [30]:
print(array5[:,0:4])

[[ 3 43 82  4]
 [ 7 15 89 68]
 [43 15 62 92]
 [86  9 21 25]
 [15 57 89 90]]


In [32]:
print(array5[:,4])

[26  1 30 39 30]


In [31]:
print(array5[:2,:])

[[ 3 43 82  4 26 28 33  9  7  7]
 [ 7 15 89 68  1 64 58 13 49 47]]
